image: golang:1.14

before_script:
  - export DOCKER_REPOSITORY="mendersoftware/mender-stress-test-client"
  - export DOCKER_TAG=${CI_COMMIT_REF_SLUG:-master}
  - export SERVICE_IMAGE=$DOCKER_REPOSITORY:$DOCKER_TAG
  - export COMMIT_TAG="$CI_COMMIT_REF_SLUG"_"$CI_COMMIT_SHA"

stages:
  - test
  - build
  - publish

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits-signoffs.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

test:format:
  stage: test
  before_script:
    - mkdir -p /go/src/github.com/mendersoftware
    - cp -r $CI_PROJECT_DIR /go/src/github.com/mendersoftware/mender-stress-test-client
    - cd /go/src/github.com/mendersoftware/mender-stress-test-client
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

build:
  image: docker
  services:
    - docker:19.03.5-dind
  stage: build
  script:
    - echo "building mender-stress-test-client for ${SERVICE_IMAGE}"
    - docker build -t $SERVICE_IMAGE .
    - docker save $SERVICE_IMAGE > image.tar
  artifacts:
    paths:
      - image.tar

publish:build:
  image: docker:git
  stage: publish
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker load -i image.tar
    - docker tag $SERVICE_IMAGE $DOCKER_REPOSITORY:$COMMIT_TAG
    - docker tag $SERVICE_IMAGE $DOCKER_REPOSITORY:$CI_COMMIT_REF_SLUG
    # We don't have stable releases nor tags for this repo, so we tag :latest together with :master
    - docker tag $SERVICE_IMAGE $DOCKER_REPOSITORY:latest
    - echo -n $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker push $DOCKER_REPOSITORY:$COMMIT_TAG
    - docker push $SERVICE_IMAGE
    - docker push $DOCKER_REPOSITORY:latest
  only:
    - master
  tags:
    - docker
